// =============================================================================
// GhostFix — Supabase Database Type Definitions
// Keep these in sync with supabase/schema.sql
//
// This file follows the exact GenericTable / GenericSchema interface shape
// that @supabase/supabase-js v2 expects for createClient<Database>(...).
// =============================================================================

/**
 * Mirrors GenericRelationship from @supabase/postgrest-js (not publicly
 * exported from the supabase-js package, so we redeclare it here).
 */
type GenericRelationship = {
  foreignKeyName: string;
  columns: string[];
  isOneToOne?: boolean;
  referencedRelation: string;
  referencedColumns: string[];
};

export type TicketStatus =
  | "pending"
  | "analyzing"
  | "patched"
  | "resolved"
  | "escalated";

// Source is now free-text — "Web Form", "API", "Slack", "Email", or anything else.
// No hard restriction, just a string.
export type TicketSource = string;

// ---------------------------------------------------------------------------
// Row types — the exact shape Supabase returns on SELECT
// ---------------------------------------------------------------------------
export interface IncomingTicketRow {
  id: string;
  source: TicketSource;
  user_email: string;
  issue_text: string;
  status: TicketStatus;
  failing_module: string | null;
  triage_summary: string | null;
  generated_ghost_link: string | null;
  team_id: string | null;
  github_pr_url: string | null;
  real_patch_code: string | null;
  created_at: string;
}

export interface HistoricalFixRow {
  id: string;
  error_signature: string;
  proposed_solution: string;
  mock_patch_code: string;
  created_at?: string | null;
}

export interface TeamRow {
  id: string;
  name: string;
  slug: string;
  owner_email: string;
  created_at: string;
}

export interface TeamMemberRow {
  id: string;
  team_id: string;
  email: string;
  role: "owner" | "member";
  created_at: string;
}

export interface TeamRepoRow {
  id: string;
  team_id: string;
  repo_owner: string;
  repo_name: string;
  default_branch: string;
  github_pat: string;
  modules: string[];
  created_at: string;
}

// ---------------------------------------------------------------------------
// Insert types — fields required when calling .insert()
// id and created_at are auto-generated by the DB so they are optional here.
// ---------------------------------------------------------------------------
export interface IncomingTicketInsert {
  id?: string;
  source: TicketSource;
  user_email: string;
  issue_text: string;
  status?: TicketStatus;
  failing_module?: string | null;
  triage_summary?: string | null;
  generated_ghost_link?: string | null;
  team_id?: string | null;
  github_pr_url?: string | null;
  real_patch_code?: string | null;
  created_at?: string;
}

export interface HistoricalFixInsert {
  id?: string;
  error_signature: string;
  proposed_solution: string;
  mock_patch_code: string;
}

// ---------------------------------------------------------------------------
// Update types — all fields optional for partial PATCH updates
// ---------------------------------------------------------------------------
export interface IncomingTicketUpdate {
  id?: string;
  source?: TicketSource;
  user_email?: string;
  issue_text?: string;
  status?: TicketStatus;
  failing_module?: string | null;
  triage_summary?: string | null;
  generated_ghost_link?: string | null;
  team_id?: string | null;
  github_pr_url?: string | null;
  real_patch_code?: string | null;
  created_at?: string;
}

export interface HistoricalFixUpdate {
  id?: string;
  error_signature?: string;
  proposed_solution?: string;
  mock_patch_code?: string;
}

// ---------------------------------------------------------------------------
// Full Database interface — must satisfy GenericSchema from @supabase/supabase-js.
// Relationships must be typed as GenericRelationship[] (not the tuple `[]`).
// Views, Functions, Enums, CompositeTypes are required keys in GenericSchema.
// ---------------------------------------------------------------------------
export interface Database {
  public: {
    Tables: {
      incoming_tickets: {
        Row: IncomingTicketRow;
        Insert: IncomingTicketInsert;
        Update: IncomingTicketUpdate;
        Relationships: GenericRelationship[];
      };
      historical_fixes: {
        Row: HistoricalFixRow;
        Insert: HistoricalFixInsert;
        Update: HistoricalFixUpdate;
        Relationships: GenericRelationship[];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
